# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bessel_i_approx <- function(x, nu) {
    .Call('_sphereGLM_bessel_i_approx', PACKAGE = 'sphereGLM', x, nu)
}

modified_bessel_i <- function(nu, x) {
    .Call('_sphereGLM_modified_bessel_i', PACKAGE = 'sphereGLM', nu, x)
}

rcpp_hello_world <- function() {
    .Call('_sphereGLM_rcpp_hello_world', PACKAGE = 'sphereGLM')
}

sphereGLM_iteration <- function(X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal) {
    .Call('_sphereGLM_sphereGLM_iteration', PACKAGE = 'sphereGLM', X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal)
}

Cq_cpp <- function(theta, logarithm = TRUE) {
    .Call('_sphereGLM_Cq_cpp', PACKAGE = 'sphereGLM', theta, logarithm)
}

Bq_cpp <- function(theta) {
    .Call('_sphereGLM_Bq_cpp', PACKAGE = 'sphereGLM', theta)
}

Hq_cpp <- function(theta) {
    .Call('_sphereGLM_Hq_cpp', PACKAGE = 'sphereGLM', theta)
}

subgrad <- function(theta) {
    .Call('_sphereGLM_subgrad', PACKAGE = 'sphereGLM', theta)
}

b1_vMF <- function(theta) {
    .Call('_sphereGLM_b1_vMF', PACKAGE = 'sphereGLM', theta)
}

b2_vMF <- function(theta) {
    .Call('_sphereGLM_b2_vMF', PACKAGE = 'sphereGLM', theta)
}

diag_matrix <- function(X, lambda) {
    .Call('_sphereGLM_diag_matrix', PACKAGE = 'sphereGLM', X, lambda)
}

calculate_b1_vMF <- function(Offset, Xt_list, beta, n) {
    .Call('_sphereGLM_calculate_b1_vMF', PACKAGE = 'sphereGLM', Offset, Xt_list, beta, n)
}

calculate_b2_vMF <- function(Offset, Xt_list, beta, n) {
    .Call('_sphereGLM_calculate_b2_vMF', PACKAGE = 'sphereGLM', Offset, Xt_list, beta, n)
}

